import type { PalLine, PalStop } from "clip-pal";

// Where the walking pal stops on the homepage, and what he says there.
//
// Every stop is anchored to a real element on the page — he stands next to
// the hero headline, the features heading, by the press clippings, by the
// terminal card, by the news heading, by the feedback form — and rides along
// with it as the page scrolls. `id` is the section that owns him, `anchor`
// the element he stands next to. Both must exist in page.tsx.
export const STOPS: readonly PalStop[] = [
  {
    id: "hero",
    anchor: "pal-hero-anchor",
    place: "beside", // right of "Your keys.", in the headline's air
    gap: 96, // clear the longer "Your people." line above him
    lines: [
      ["hey — i'm clip pal. i hold this whole thing together.", "wave"],
      ["it looks like you're trying to leave big tech. want a hand?", "question"],
      ["one clip, zero data harvested. good start, right?", "nod"],
      ["i've been holding this page together since the top.", "lean"],
      ["welcome. mind the wire, it's load-bearing.", "wave"],
      ["mascot and structural support. busy job, honestly.", "unbend"],
      ["first time here? there's not much to sign up for.", "question"],
      ["scroll on. i'll keep up. probably.", "hop"],
      ["made of one bent wire and a lot of opinions.", "unbend"],
      ["no cookie banner. i checked. twice.", "look"],
      ["i'd offer you a tour, but you're already on it.", "spin"],
      ["bit of an odd mascot, i'll admit. grew on people.", "curl"],
      ["you can read the whole page. it's short, i promise.", "nod"],
      ["the name's clip pal. the pun was not my idea.", "shake"],
      ["tap tap. hello? anyone still out there?", "knock"],
      ["come closer, i want to tell you something.", "lean"],
      ["found a ball. watch this.", "kick"],
      ["your keys. as in, literally yours. i can do the shape.", "key"],
      ["oh! a visitor. i wasn't ready. i'm ready now.", "exclaim"],
      ["thank you, thank you. no autographs, i'm made of wire.", "bow"],
    ],
  },
  {
    id: "features",
    anchor: "pal-features-anchor",
    place: "beside",
    lines: [
      ["no ads, no tracking, no catch. all of it, yours.", "shake"],
      ["encrypted on your phone, unreadable everywhere else.", "curl"],
      ["no phone number, no real name, no problem.", "shake"],
      ["your keys stay in your pocket. that's the whole trick.", "key"],
      ["small circles beat a firehose. every time.", "nod"],
      ["nobody's optimising you for engagement here.", "shake"],
      ["boring privacy defaults. the good kind of boring.", "nod"],
      ["yeah, it's free. no, there's no catch tier.", "nod"],
      ["we can't read your messages. that's not modesty.", "shake"],
      ["nothing here learns your habits. it just delivers.", "shake"],
      ["self-host it if you'd rather not trust anyone. fair.", "question"],
      ["an app that doesn't want your attention. imagine.", "look"],
      ["no engagement metrics. nobody's chasing your time.", "shake"],
      ["the good stuff is on by default. no settings dive.", "nod"],
      ["psst. this next bit is my favourite.", "lean"],
      ["look, i can jump. that's the whole trick.", "hop"],
      ["just checking on the competition. still all ads.", "look"],
      ["six features, one leg. i manage.", "backflip"],
      ["end-to-end. as in, from your end to their end. no middle.", "key"],
      ["wait — did i leave the crypto on? …yes. it's always on.", "exclaim"],
    ],
  },
  {
    id: "why",
    anchor: "pal-why-anchor",
    place: "gutter-left",
    lines: [
      ["remember when software was on your side? same.", "nod"],
      ["your feed used to be yours. let's do that again.", "heart"],
      ["90s helpfulness, 2026 cryptography. weird mix, i know.", "wave"],
      ["i miss when apps just did the thing you asked.", "look"],
      ["somewhere along the way, the feed stopped being yours.", "shake"],
      ["we're not reinventing anything. just handing it back.", "shake"],
      ["old-fashioned? maybe. it worked, though.", "question"],
      ["you're the user here, not the product. novel, i know.", "heart"],
      ["nobody set out to make the internet worse. and yet.", "shake"],
      ["the web used to feel like a place. it can again.", "lean"],
      ["turns out you can just... not sell people's data.", "shake"],
      ["everything got louder. this is the quiet corner.", "curl"],
      ["small software, made on purpose. that's the pitch.", "nod"],
      ["if this feels slower, that's deliberate. enjoy it.", "unbend"],
      ["hang on — i need a proper stretch.", "unbend"],
      ["one leg and still bouncing. respect that.", "hop"],
      ["peeked at the big corporate networks. came straight back.", "look"],
      ["brr. i read a data broker's terms of service once. still cold.", "shiver"],
      ["these clippings? real headlines. i just hold them up.", "bow"],
    ],
  },
  {
    id: "opensource",
    anchor: "pal-open-anchor",
    place: "gutter-right",
    lines: [
      ["every line is public. read it, fork it, trust it.", "lean"],
      ["don't trust us — trust the code. it's all right there.", "lean"],
      ["built in the open, by people who actually use it.", "nod"],
      ["go read it. i'll wait, i've got nowhere to be.", "curl"],
      ["if we were lying, the source would tell on us.", "shake"],
      ["fork it and make it weird. genuinely, go ahead.", "dance"],
      ["no secret sauce. just sauce, in a public repo.", "shake"],
      ["audited by whoever feels like it. that's the point.", "nod"],
      ["found a bug? tell us. or fix it. either's great.", "question"],
      ["the crypto is the boring, well-reviewed kind.", "nod"],
      ["you don't have to like us. just check our work.", "look"],
      ["issues are open. opinions welcome, patches better.", "wave"],
      ["clone it, run it, keep it. it's yours now too.", "heart"],
      ["open source isn't a feature. it's the arrangement.", "nod"],
      ["ta-da. i've been practising that one.", "spin"],
      ["give it a boot and it still works. sturdy, this.", "kick"],
      ["i'm on npm now, by the way. `npm i clip-pal`. i'm very portable.", "backflip"],
      ["yes, even i am open source. every bend of me.", "unbend"],
    ],
  },
  {
    id: "news",
    anchor: "pal-news-anchor",
    place: "beside",
    lines: [
      ["fresh off the press: android comes first.", "hop"],
      ["that's the tour. built with a paperclip and stubbornness.", "spin"],
      ["news travels fast when there are no algorithms.", "nod"],
      ["stick around. or self-host. or both. i'm easy.", "question"],
      ["you made it to the bottom. thorough of you.", "nod"],
      ["that's everything. no newsletter popup, promise.", "shake"],
      ["android first, then the rest. one thing at a time.", "hop"],
      ["okay, that's my whole routine. thanks for scrolling.", "dance"],
      ["we ship when it's ready. novel approach, apparently.", "nod"],
      ["no launch hype. just a build, when there's a build.", "shake"],
      ["still here? you're my favourite kind of visitor.", "heart"],
      ["that's the footer down there. mind the step.", "look"],
      ["go on then. the github link's right below me.", "lean"],
      ["same time next scroll? i'll be around.", "wave"],
      ["ahh. that's the good kind of straight.", "unbend"],
      ["oops. that'll buff out, probably.", "crack"],
      ["no release date. i know. i asked too.", "exclaim"],
    ],
  },
  {
    id: "feedback",
    anchor: "pal-feedback-anchor",
    place: "gutter-left",
    lines: [
      ["found a bug? tell us. i'll pretend it wasn't me.", "look"],
      ["type it in. a human reads it, not a model. i just carry it.", "nod"],
      ["be honest. i've heard worse. mostly about the leg.", "shake"],
      ["compliments also accepted. i'm not proud.", "heart"],
      ["no account, no login. just a box and a button.", "nod"],
      ["your message goes to a mailbox, not a database. i checked.", "key"],
      ["is the paperclip creepy? you can say. i can take it.", "question"],
      ["leave an email and a real person writes back. wild, right?", "exclaim"],
      ["i deliver every one of these personally. by wire.", "wave"],
      ["say something nice and i'll do a flip. no pressure.", "backflip"],
      ["this is the part where you talk. i'll listen.", "lean"],
      ["ideas welcome. even the weird ones. especially those.", "spin"],
    ],
  },
];

// When the page sits still (no mouse, scroll, key or touch) he stops waiting
// on the scroll anchors, wanders off to the other side of the screen and says
// one of these. The moment the visitor does anything again, he heads back.
export const IDLE_LINES: readonly PalLine[] = [
  ["you still there? wandered off to stretch my wire.", "unbend"],
  ["quiet in here. i'll keep your seat warm.", "curl"],
  ["no rush — wiggle the mouse when you're back.", "knock"],
  ["just me and the paperclips. peaceful, honestly.", "look"],
  ["i'll be here. not like i've got other pages to be on.", "shake"],
  ["taking five. scroll whenever you're ready.", "curl"],
  ["went to look out the window. nothing out there.", "look"],
  ["no notifications to check. strange feeling, isn't it?", "question"],
  ["still holding everything together, in case you wondered.", "nod"],
  ["i counted the pixels. there are a lot of them.", "look"],
  ["coffee? i'd offer, but i'm made of wire.", "question"],
  ["nothing's loading. it's just quiet. that's allowed.", "curl"],
  ["i'm not tracking how long you've been gone. promise.", "shake"],
  ["found a nice patch of whitespace over here.", "look"],
  ["if you left the tab open on purpose, respect.", "nod"],
  ["somewhere a server is idling with me. solidarity.", "heart"],
  ["take your time. the page isn't going anywhere.", "nod"],
  ["i straightened myself out a bit. bent back now.", "unbend"],
  ["knock knock. you awake in there?", "knock"],
  ["nobody's watching. might as well dance.", "dance"],
  ["hello? tap the glass if you're still there.", "knock"],
  ["looking left, looking right. no algorithms either way.", "look"],
  ["...i'll pay for the screen. put it on my tab.", "crack"],
  ["…zzz. oh. you're back. i wasn't asleep.", "doze"],
  ["resting my eyes. the wire never sleeps, but the eyes do.", "doze"],
  ["draughty on this side of the screen. brr.", "shiver"],
  ["nobody around. perfect time to practise the flip.", "backflip"],
  ["and for my next trick — nothing. i'm off duty.", "bow"],
];
